name: ci
on:
  push: { branches: [main] }
  pull_request:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install -U pip  # co robi: aktualizuje pip
      - run: pip install -r requirements.txt pytest ruff mypy types-requests  # co robi: instaluje zależności i narzędzia
      - run: pytest -q  # co robi: uruchamia testy
      - run: ruff check .  # co robi: lint
      - run: mypy .  # co robi: sprawdzanie typów
